### PR TITLE
chore: adapt codebase

### PR DESCRIPTION
**Pull request by marcoskichel**
## Description
This is an umbrella for all the initial changes made against the original `fork-sync` codebase. Please review the below PR's individually:

- https://github.com/ExodusMovement/fork-sync/pull/2
- https://github.com/ExodusMovement/fork-sync/pull/4

### CODE REVIEW

**Review by sparten11740 — APPROVED** [review]

**Comment by marcoskichel** [comment]
In terms of repo settings, how should I proceed? Should I set someone else as admin or use any default settings shared across all our repos?  

@mvayngrib @sparten11740

**Comment by sparten11740** [comment]
>  Should I set someone else as admin or use any default settings shared across all our repos?

you can make me admin as well and I will adjust the settings

**Comment by mvayngrib** [comment]
recommended settings here https://coda.io/d/Engineering-Handbook_dWMI1pUBpME/Checklist-Before-You-Open-Source-a-Github-Repo_suCMu#_luYlx

we have a little tool to set the right settings https://github.com/ExodusMovement/exodus-hydra/blob/5bbac9011f606c979b7b16abc146a102d5e2d477/libraries/github-security-checks/README.md#

should go roughly like this. I realize it's already public, so some of these may look weird
```
# 1. add Vlad and myself as codeowners for the .github folder (633kh4ck and mvayngrib)
# 2. set some settings and verify codeowners for .github folder (you'll need to add them first)
npx @exodus/github-security-checks secure-private --repo ExodusMovement/fork-sync --token $(op read op://private/github/accesstoken -n 2> /dev/null) -c 633kh4ck -c mvayngrib
# 3. make it public and add additional security settings that can only be enabled when public
npx @exodus/github-security-checks make-public --repo ExodusMovement/fork-sync --token $(op read op://private/github/accesstoken -n 2> /dev/null) -c 633kh4ck -c mvayngrib
```

**Comment by mvayngrib** [comment]
@marcoskichel next time let's merge parent first, then rebase child, then child, etc. Or was there a reason to do it the other way here?

**Comment by marcoskichel** [comment]
> @marcoskichel next time let's merge parent first, then rebase child, then child, etc. Or was there a reason to do it the other way here?

Sure, the reason I did it like that was because the changes here were all related IMO, like cleaning up that codebase to use our standards, but I didn't want to have 999 files polluting the review.

I will make sure to use the approach you suggested next time

@mvayngrib

**Comment by mvayngrib** [comment]
yes but now we're reviewing the merged changeset so kind of defeats the purpose 🤔

**Review by mvayngrib — APPROVED** [review]
utACK

**Pull request merged**
