### PR TITLE
feat: allow specifying head_repo

### PR DESCRIPTION
**Pull request by marcoskichel**
## Description

It seems like the original action don't support synchronizing forks that are under the same org, this PR changes that by introuducing a new `head_repo` input which allow us to define a different name for the head repo

### CODE REVIEW

**Comment by mvayngrib** [comment]
this still needed @marcoskichel ?

**Comment by marcoskichel** [comment]
> this still needed @marcoskichel ?

Yes, otherwise it won't work with forks within the same organization

**Comment by marcoskichel** [comment]
Can we merge this?

**Review by mvayngrib — APPROVED** [review]

**Comment by mvayngrib** [comment]
please do

**Pull request merged**
